export const universiteler: { ad: string; sehir: string }[] = [
  { ad: "Abant İzzet Baysal Üniversitesi", sehir: "Bolu" },
  { ad: "Abdullah Gül Üniversitesi", sehir: "Kayseri" },
  { ad: "Adıyaman Üniversitesi", sehir: "Adıyaman" },
  { ad: "Afyon Kocatepe Üniversitesi", sehir: "Afyonkarahisar" },
  { ad: "Ağrı İbrahim Çeçen Üniversitesi", sehir: "Ağrı" },
  { ad: "Aksaray Üniversitesi", sehir: "Aksaray" },
  { ad: "Amasya Üniversitesi", sehir: "Amasya" },
  { ad: "Anadolu Üniversitesi", sehir: "Eskişehir" },
  { ad: "Ankara Üniversitesi", sehir: "Ankara" },
  { ad: "Ankara Hacı Bayram Veli Üniversitesi", sehir: "Ankara" },
  { ad: "Ankara Medipol Üniversitesi", sehir: "Ankara" },
  { ad: "Ankara Sosyal Bilimler Üniversitesi", sehir: "Ankara" },
  { ad: "Ankara Yıldırım Beyazıt Üniversitesi", sehir: "Ankara" },
  { ad: "Ardahan Üniversitesi", sehir: "Ardahan" },
  { ad: "Artvin Çoruh Üniversitesi", sehir: "Artvin" },
  { ad: "Atatürk Üniversitesi", sehir: "Erzurum" },
  { ad: "Balıkesir Üniversitesi", sehir: "Balıkesir" },
  { ad: "Bartın Üniversitesi", sehir: "Bartın" },
  { ad: "Batman Üniversitesi", sehir: "Batman" },
  { ad: "Bayburt Üniversitesi", sehir: "Bayburt" },
  { ad: "Bilecik Şeyh Edebali Üniversitesi", sehir: "Bilecik" },
  { ad: "Bingöl Üniversitesi", sehir: "Bingöl" },
  { ad: "Bitlis Eren Üniversitesi", sehir: "Bitlis" },
  { ad: "Boğaziçi Üniversitesi", sehir: "İstanbul" },
  { ad: "Burdur Mehmet Akif Ersoy Üniversitesi", sehir: "Burdur" },
  { ad: "Bursa Teknik Üniversitesi", sehir: "Bursa" },
  { ad: "Bursa Uludağ Üniversitesi", sehir: "Bursa" },
  { ad: "Çanakkale Onsekiz Mart Üniversitesi", sehir: "Çanakkale" },
  { ad: "Çankırı Karatekin Üniversitesi", sehir: "Çankırı" },
  { ad: "Çukurova Üniversitesi", sehir: "Adana" },
  { ad: "Dicle Üniversitesi", sehir: "Diyarbakır" },
  { ad: "Dokuz Eylül Üniversitesi", sehir: "İzmir" },
  { ad: "Düzce Üniversitesi", sehir: "Düzce" },
  { ad: "Ege Üniversitesi", sehir: "İzmir" },
  { ad: "Erzincan Binali Yıldırım Üniversitesi", sehir: "Erzincan" },
  { ad: "Erzurum Teknik Üniversitesi", sehir: "Erzurum" },
  { ad: "Eskişehir Osmangazi Üniversitesi", sehir: "Eskişehir" },
  { ad: "Eskişehir Teknik Üniversitesi", sehir: "Eskişehir" },
  { ad: "Fırat Üniversitesi", sehir: "Elazığ" },
  { ad: "Galatasaray Üniversitesi", sehir: "İstanbul" },
  { ad: "Gaziantep Üniversitesi", sehir: "Gaziantep" },
  { ad: "Gebze Teknik Üniversitesi", sehir: "Kocaeli" },
  { ad: "Giresun Üniversitesi", sehir: "Giresun" },
  { ad: "Gümüşhane Üniversitesi", sehir: "Gümüşhane" },
  { ad: "Hacettepe Üniversitesi", sehir: "Ankara" },
  { ad: "Hakkari Üniversitesi", sehir: "Hakkari" },
  { ad: "Harran Üniversitesi", sehir: "Şanlıurfa" },
  { ad: "Hatay Mustafa Kemal Üniversitesi", sehir: "Hatay" },
  { ad: "Hitit Üniversitesi", sehir: "Çorum" },
  { ad: "Iğdır Üniversitesi", sehir: "Iğdır" },
  { ad: "Isparta Uygulamalı Bilimler Üniversitesi", sehir: "Isparta" },
  { ad: "İnönü Üniversitesi", sehir: "Malatya" },
  { ad: "İstanbul Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Üniversitesi-Cerrahpaşa", sehir: "İstanbul" },
  { ad: "İstanbul Teknik Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Medeniyet Üniversitesi", sehir: "İstanbul" },
  { ad: "Kahramanmaraş Sütçü İmam Üniversitesi", sehir: "Kahramanmaraş" },
  { ad: "Karabük Üniversitesi", sehir: "Karabük" },
  { ad: "Karadeniz Teknik Üniversitesi", sehir: "Trabzon" },
  { ad: "Kastamonu Üniversitesi", sehir: "Kastamonu" },
  { ad: "Kayseri Üniversitesi", sehir: "Kayseri" },
  { ad: "Kırıkkale Üniversitesi", sehir: "Kırıkkale" },
  { ad: "Kırklareli Üniversitesi", sehir: "Kırklareli" },
  { ad: "Kırşehir Ahi Evran Üniversitesi", sehir: "Kırşehir" },
  { ad: "Kilis 7 Aralık Üniversitesi", sehir: "Kilis" },
  { ad: "Kocaeli Üniversitesi", sehir: "Kocaeli" },
  { ad: "Konya Teknik Üniversitesi", sehir: "Konya" },
  { ad: "Kütahya Dumlupınar Üniversitesi", sehir: "Kütahya" },
  { ad: "Malatya Turgut Özal Üniversitesi", sehir: "Malatya" },
  { ad: "Manisa Celal Bayar Üniversitesi", sehir: "Manisa" },
  { ad: "Mardin Artuklu Üniversitesi", sehir: "Mardin" },
  { ad: "Mersin Üniversitesi", sehir: "Mersin" },
  { ad: "Mimar Sinan Güzel Sanatlar Üniversitesi", sehir: "İstanbul" },
  { ad: "Muğla Sıtkı Koçman Üniversitesi", sehir: "Muğla" },
  { ad: "Munzur Üniversitesi", sehir: "Tunceli" },
  { ad: "Muş Alparslan Üniversitesi", sehir: "Muş" },
  { ad: "Nevşehir Hacı Bektaş Veli Üniversitesi", sehir: "Nevşehir" },
  { ad: "Niğde Ömer Halisdemir Üniversitesi", sehir: "Niğde" },
  { ad: "Ondokuz Mayıs Üniversitesi", sehir: "Samsun" },
  { ad: "Ordu Üniversitesi", sehir: "Ordu" },
  { ad: "Orta Doğu Teknik Üniversitesi", sehir: "Ankara" },
  { ad: "Osmaniye Korkut Ata Üniversitesi", sehir: "Osmaniye" },
  { ad: "Pamukkale Üniversitesi", sehir: "Denizli" },
  { ad: "Recep Tayyip Erdoğan Üniversitesi", sehir: "Rize" },
  { ad: "Sakarya Üniversitesi", sehir: "Sakarya" },
  { ad: "Selçuk Üniversitesi", sehir: "Konya" },
  { ad: "Siirt Üniversitesi", sehir: "Siirt" },
  { ad: "Sinop Üniversitesi", sehir: "Sinop" },
  { ad: "Sivas Cumhuriyet Üniversitesi", sehir: "Sivas" },
  { ad: "Şırnak Üniversitesi", sehir: "Şırnak" },
  { ad: "Tekirdağ Namık Kemal Üniversitesi", sehir: "Tekirdağ" },
  { ad: "Tokat Gaziosmanpaşa Üniversitesi", sehir: "Tokat" },
  { ad: "Trabzon Üniversitesi", sehir: "Trabzon" },
  { ad: "Türk-Alman Üniversitesi", sehir: "İstanbul" },
  { ad: "Uşak Üniversitesi", sehir: "Uşak" },
  { ad: "Van Yüzüncü Yıl Üniversitesi", sehir: "Van" },
  { ad: "Yalova Üniversitesi", sehir: "Yalova" },
  { ad: "Yozgat Bozok Üniversitesi", sehir: "Yozgat" },
  { ad: "Zonguldak Bülent Ecevit Üniversitesi", sehir: "Zonguldak" },
  { ad: "Acıbadem Mehmet Ali Aydınlar Üniversitesi", sehir: "İstanbul" },
  { ad: "Altınbaş Üniversitesi", sehir: "İstanbul" },
  { ad: "Atılım Üniversitesi", sehir: "Ankara" },
  { ad: "Avrasya Üniversitesi", sehir: "Trabzon" },
  { ad: "Bahçeşehir Üniversitesi", sehir: "İstanbul" },
  { ad: "Başkent Üniversitesi", sehir: "Ankara" },
  { ad: "Beykent Üniversitesi", sehir: "İstanbul" },
  { ad: "Beykoz Üniversitesi", sehir: "İstanbul" },
  { ad: "Bezmiâlem Vakıf Üniversitesi", sehir: "İstanbul" },
  { ad: "Bilgi Üniversitesi", sehir: "İstanbul" },
  { ad: "Bilkent Üniversitesi", sehir: "Ankara" },
  { ad: "Biruni Üniversitesi", sehir: "İstanbul" },
  { ad: "Çağ Üniversitesi", sehir: "Mersin" },
  { ad: "Çankaya Üniversitesi", sehir: "Ankara" },
  { ad: "Doğuş Üniversitesi", sehir: "İstanbul" },
  { ad: "Fenerbahçe Üniversitesi", sehir: "İstanbul" },
  { ad: "Haliç Üniversitesi", sehir: "İstanbul" },
  { ad: "İbn Haldun Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul 29 Mayıs Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Aydın Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Bilgi Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Esenyurt Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Gelişim Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Kültür Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Medipol Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Nişantaşı Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Okan Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Sabahattin Zaim Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Ticaret Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Topkapı Üniversitesi", sehir: "İstanbul" },
  { ad: "İstanbul Yeni Yüzyıl Üniversitesi", sehir: "İstanbul" },
  { ad: "İstinye Üniversitesi", sehir: "İstanbul" },
  { ad: "İzmir Ekonomi Üniversitesi", sehir: "İzmir" },
  { ad: "Kadir Has Üniversitesi", sehir: "İstanbul" },
  { ad: "Koç Üniversitesi", sehir: "İstanbul" },
  { ad: "Maltepe Üniversitesi", sehir: "İstanbul" },
  { ad: "MEF Üniversitesi", sehir: "İstanbul" },
  { ad: "Özyeğin Üniversitesi", sehir: "İstanbul" },
  { ad: "Sabancı Üniversitesi", sehir: "İstanbul" },
  { ad: "TED Üniversitesi", sehir: "Ankara" },
  { ad: "TOBB Ekonomi ve Teknoloji Üniversitesi", sehir: "Ankara" },
  { ad: "Ufuk Üniversitesi", sehir: "Ankara" },
  { ad: "Üsküdar Üniversitesi", sehir: "İstanbul" },
  { ad: "Yaşar Üniversitesi", sehir: "İzmir" },
  { ad: "Yeditepe Üniversitesi", sehir: "İstanbul" },
]
